config/routes.rb
PersonalWebsite::Application.routes.draw do

  root "static_pages#home"

  get "about" => "static_pages#about"
  get "projects" => "static_pages#projects"
  get "resume" => "static_pages#resume"
  get "contact" => "static_pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def resume
    # send_file('/Users/magdalenelim/Desktop/rails_apps/personal_website/app/assets/', :filename => 'Resume-1copy.pdf', :disposition => 'inline', :type => "application/pdf") 
    pdf
  end

  def contact
  end

  def pdf
    pdf_filename = File.join(Rails.root, "app/assets/Resume-1copy.pdf")
    send_file(pdf_filename, :filename => "Resume-1copy.pdf",:disposition => 'inline', :type => "application/pdf")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class="navbar-brand">Magdalene Lim</div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Projects", projects_path %></li> 
          <li><%= link_to "Resume", resume_path %></li> 
          <li><%= link_to "Contact", contact_path %></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div> <!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalWebsite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render(:partial => 'layouts/header') if (params[:action] != 'home') %>
	<%= yield %>
<!-- render footer -->
</body>
</html>

app/views/static_pages/about.html.erb
<div class="body2">
	<h1>About me</h1>

	<div class="portrait">
		<%= image_tag("self1.jpg") %>
	</div>

	<div class="description">Welcome to my website!</div><br>
	<div class="description">I'm a third year Computer Science major at UC Berkeley. </div><br>
	<div class="description">Coding makes me feel like a magician.</div><br>
	<div class="description">I like ice cream.</div><br>

</div>

app/views/static_pages/contact.html.erb
<div class="body2">
	<h1>Contact</h1>
	<div class="description">You can reach me at: or through this form!!</div>
</div>

app/views/static_pages/projects.html.erb
<div class="body2">
	<h1>Projects</h1>
	<div class="description">Coming soon!</div>
</div>

app/views/static_pages/resume.html.erb
<h1>StaticPages#resume</h1>
<p>Find me in app/views/static_pages/resume.html.erb</p>